# Version of the config file. Used to alert on breaking changes in configs.
version: 1.0

# Maximum number of fragments in a final assembly
# limited by Gibson diminishing efficiency with fragment count
fragments-max-count: 6

# Minimum homology length between fragments
fragments-min-junction-length: 20

# Maximum homology length between fragments
fragments-max-junction-length: 120

# Maximum allowable hairpin melting temperature (celsius)
fragments-max-junction-hairpin: 47.0

# Cost per Gibson assembly reaction
# $649.00 / 50
# from https://www.neb.com/products/e2611-gibson-assembly-master-mix#Product%20Information
gibson-assembly-cost: 12.98

# Cost per Gibson Assembly in human time
gibson-assembly-time-cost: 0.0

# Cost per bp of PCR primer. based on IDT prices
pcr-bp-cost: 0.6

# Cost per PCR reaction
# $54.75 / 200
# estimated from manual at https://www.thermofisher.com/order/catalog/product/18067017
pcr-rxn-cost: 0.27

# Cost per PCR in human time
pcr-time-cost: 0.0

# Minimum length of a PCR fragment
pcr-min-length: 200

# Max primer3 pair penalty score
pcr-primer-max-pair-penalty: 30.0

# Max embedded length. The most bp to include upstream of a annealing portion
# of a primer to create or extend a junction with another part
pcr-primer-max-embed-length: 40

# Max off-target primer binding site Tm, above which a PCR is abandoned
pcr-primer-max-ectopic-tm: 55.0

# The length of PCR buffer. The length of the ranges to allow Primer3 to
# choose primers in if neighbors are both synthetic. The larger this number,
# the "better" the primers may be, but at the cost of a more expensive plasmid
# (more synthesis)
pcr-buffer-length: 10

# primer3 min and max primer lengths
# are also used for estimating 
# the cost of a PCR fragment before primers are computed
# by taking the median value between min and max size

# primer3 min primer length
pcr-min-primer-length: 18

# primer3 max primer length
pcr-max-primer-length: 30

# primer3 optimum primer length
pcr-optimum-primer-length: 20

# Min annealing temperature (Tm) used by primer3 to calculate primers
pcr-primer-min-tm: 57

# Max annealing temperature (Tm) used by primer3 to calculate primers
pcr-primer-max-tm: 63

# Max allowed difference in primer annealing temperatures (Tm)
# If <0 the difference is not checked
pcr-max-fwd-rev-primer-tm-diff: 5

# Minimum length of a synthesized building fragment
synthetic-min-length: 300

# Maximum length of a synthesized building fragment
synthetic-max-length: 1800

# Penalty for synthetic fragments
synthetic-fragment-factor: 1

# Cost of synthesis (step-function)
# the key here is the upper limit on the synthesis to that range
# so 500: is synthesis from whatever length is less than that key up to it
synthetic-fragment-cost:
  # Twist: 
  1800:
    fixed: false
    cost: 0.07

# Cost of synthesis and delivery in a plasmid
# Twist: https://www.twistbioscience.com/products/genes?tab=clonal
synthetic-plasmid-cost:
  5000:
    fixed: false
    cost: 0.09
